[package]
name = "psxmcrw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psxmem = "0.1.2"
rppal = "0.13.1"
thiserror = "1.0.37"
